### PR TITLE
Fixing the "Posts.hasresolved is not a function" bug

### PR DESCRIPTION
**Pull request by JuliaZhang7**
By adding resolve function in the tools folder, this function should be working now. 
Resolve is a function that can be toggled, and will maintain as a property of the post

### CODE REVIEW

**Comment by JuliaZhang7** [comment]
@sunnyt02 for a change in frontend button design

**Comment by sunnyt02** [comment]
> @sunnyt02 for a change in frontend button design

#26

**Review by sunnyt02 — APPROVED** [review]
unit tests done with a "mark as resolved" button; observed desired changes in post's status

**Review by victorwa22 — COMMENTED** [review]
Resolved function passes newly written tests as intended

**Pull request merged**
